Q1 1) Downloading the dataset

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
LR = LinearRegression() #LR is an instance of the class LinearRegression
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
model=LogisticRegression(solver='liblinear', random_state=0)
!gdown --id 1Of2FBm6tNPFUs-QoTuWDBwmgwy2nPZ4W

Downloading...
From: https://drive.google.com/uc?id=1Of2FBm6tNPFUs-QoTuWDBwmgwy2nPZ4W
To: /content/Real estate valuation data set.csv
100% 22.0k/22.0k [00:00<00:00, 19.4MB/s]

Q1 2) Doing the pre-processing

In [27]:
df1=pd.read_csv('/content/Real estate valuation data set.csv')
df1=df1.iloc[1:df1.shape[0],1:8]  #Selecting all the rows except the first and all the columns except the last two as they are redundant.
display(df1)

     X1 transaction date  ...  Y house price of unit area
1               2012.917  ...                        42.2
2               2013.583  ...                        47.3
3               2013.500  ...                        54.8
4               2012.833  ...                        43.1
5               2012.667  ...                        32.1
..                   ...  ...                         ...
409             2013.000  ...                        15.4
410             2012.667  ...                        50.0
411             2013.250  ...                        40.6
412             2013.000  ...                        52.5
413             2013.500  ...                        63.9

[413 rows x 7 columns]

Q1 3,4,5,6,7) Splitting and training the data

In [28]:
split_ratio=[0.8,0.6,0.7,0.9] #Ratios to be used for the question
for n in split_ratio:
    print('\033[1m' + 'Linear Regression analysis for split ratio ' + str(int(n*100)) +":"+ str(int(100- n*100)) + '\033[0m')
    n_rows=np.ceil(n*413) #number of rows to be included in the train data

    train_data=df1.iloc[0:int(n_rows)]      #Defining the test and train data
    test_data=pd.DataFrame(df1.iloc[int(n_rows):df1.shape[0]])
   
    
    LR.fit(train_data.drop(columns=['Y house price of unit area']),  train_data.iloc[0:train_data.shape[0],6]) #fitting the data
    
    print("Intercept of model is", LR.intercept_)      #.intercept_ prints the intercept
    
    display(pd.DataFrame(LR.coef_,index=[1,2,3,4,5,6]).rename(columns={0:'Weights'}))  # .coef_ gives the coefficients
    print(" ")

    y_prediction=LR.predict(test_data.drop(columns=['Y house price of unit area']))  #.predict(test_data) helps to predict the data
    y_prediction_data=pd.DataFrame(y_prediction).rename(columns={0:'Predicted Prices'})
    print(" The predicted data is:")
    display(y_prediction_data)
    print(" ")

    from sklearn.metrics import mean_squared_error   #Mean Squared error
    print("Mean squared error is" , mean_squared_error(test_data.iloc[0:test_data.shape[0],6],y_prediction))
    print(" ")

    print('Coefficient of determination:', LR.score(train_data.drop(columns=['Y house price of unit area']),train_data.iloc[0:train_data.shape[0],6])) #calculating r^2 using .score(x,y)
    print(" ")
    print(" ")

Linear Regression analysis for split ratio 80:20
Intercept of model is -15390.90014024705

      Weights
1    5.059068
2   -0.283284
3   -0.004117
4    1.202368
5  251.034753
6   -8.386714

 The predicted data is:

    Predicted Prices
0          32.945548
1          43.303203
2          40.023853
3          41.627669
4          38.170056
..               ...
77         14.496533
78         50.260065
79         47.085469
80         44.482985
81         54.219313

[82 rows x 1 columns]

Mean squared error is 60.07928113584405

Coefficient of determination: 0.5807183923130059


Linear Regression analysis for split ratio 60:40
Intercept of model is -15113.117825564379

      Weights
1    3.741437
2   -0.289382
3   -0.003763
4    1.304092
5  242.867754
6   12.827798

 The predicted data is:

     Predicted Prices
0            9.745759
1           39.735191
2           22.964693
3           52.048239
4           26.319243
..                ...
160         15.191955
161         51.513975
162         47.284736
163         44.891491
164         54.370147

[165 rows x 1 columns]

Mean squared error is 98.35347380336555

Coefficient of determination: 0.6429276639923353


Linear Regression analysis for split ratio 70:30
Intercept of model is -13285.723424541446

      Weights
1    4.444370
2   -0.294853
3   -0.004259
4    1.105361
5  265.594280
6  -18.509941

 The predicted data is:

     Predicted Prices
0           45.454088
1           38.623896
2           43.104343
3           45.149067
4           31.039302
..                ...
118         14.671593
119         50.508639
120         47.078307
121         44.798016
122         53.945432

[123 rows x 1 columns]

Mean squared error is 65.82632166314235

Coefficient of determination: 0.5773421326036362


Linear Regression analysis for split ratio 90:10
Intercept of model is -15491.107894710656

      Weights
1    5.259902
2   -0.268971
3   -0.004286
4    1.153946
5  253.573993
6  -11.409818

 The predicted data is:

    Predicted Prices
0          43.808187
1          48.373938
2          30.350361
3          34.121571
4          48.865019
5          40.621424
6          51.321350
7          47.567115
8          55.220118
9          13.212891
10         37.091006
11         12.557365
12         51.623052
13         40.768020
14         31.332206
15         34.522139
16         40.443762
17         44.984423
18         31.470546
19         38.405709
20         42.806172
21         16.162887
22         39.380233
23         27.934905
24         45.895867
25         34.121571
26         39.696496
27         40.988446
28         33.151265
29         39.223743
30         45.130964
31         46.948482
32         37.128417
33         49.657610
34         26.329705
35         32.037881
36         14.087226
37         49.870154
38         47.069956
39         44.375072
40         54.009579

Mean squared error is 73.1817722547392

Coefficient of determination: 0.5832596141046056

Q1 9]

In [29]:
split_ratio=[0.8,0.6,0.7,0.9] #Ratios to be used for the question
for n in split_ratio:
    print('\033[1m' + 'Ridge Regression analysis for split ratio ' + str(int(n*100)) +":"+ str(int(100- n*100)) + '\033[0m')
    n_rows=np.ceil(n*413) #number of rows to be included in the train data

    train_data=df1.iloc[0:int(n_rows)]      #Defining the test and train data
    test_data=pd.DataFrame(df1.iloc[int(n_rows):df1.shape[0]]) 
    # Train the model
    lambda_values=[.001, 0.005, 0.01, 0.05, 0.1,0.5]
    for l in lambda_values:
        ridgeR = Ridge(alpha = l)
        ridgeR.fit(train_data.drop(columns=['Y house price of unit area']),  train_data.iloc[0:train_data.shape[0],6])
        y_pred = ridgeR.predict(test_data.drop(columns=['Y house price of unit area']))
        print("For regularisation parameter (alpha)=", l)
    
 
    # calculate mean square error
        mean_squared_error_ridge = np.mean((y_pred - test_data.iloc[0:test_data.shape[0],6])**2)
        print("Mean Squared Error is" , mean_squared_error_ridge)
    
 
     # get r^2 value for Ridge
        print("r^2 value is:",r2_score(test_data.iloc[0:test_data.shape[0],6], y_pred))
        print("")
        print("")

Ridge Regression analysis for split ratio 80:20
For regularisation parameter (alpha)= 0.001
Mean Squared Error is 59.90941086643283
r^2 value is: 0.5942114585075


For regularisation parameter (alpha)= 0.005
Mean Squared Error is 59.40557069313447
r^2 value is: 0.597624153877246


For regularisation parameter (alpha)= 0.01
Mean Squared Error is 59.03768322122167
r^2 value is: 0.6001159914450311


For regularisation parameter (alpha)= 0.05
Mean Squared Error is 58.77652205985455
r^2 value is: 0.6018849323381726


For regularisation parameter (alpha)= 0.1
Mean Squared Error is 59.15161968654281
r^2 value is: 0.5993442577321333


For regularisation parameter (alpha)= 0.5
Mean Squared Error is 60.00077636782473
r^2 value is: 0.5935926062601429


Ridge Regression analysis for split ratio 60:40
For regularisation parameter (alpha)= 0.001
Mean Squared Error is 98.27976766265618
r^2 value is: 0.49618427382131436


For regularisation parameter (alpha)= 0.005
Mean Squared Error is 98.16475306775904
r^2 value is: 0.4967738779995431


For regularisation parameter (alpha)= 0.01
Mean Squared Error is 98.23295818869761
r^2 value is: 0.4964242352057918


For regularisation parameter (alpha)= 0.05
Mean Squared Error is 99.54510990641297
r^2 value is: 0.48969769640498273


For regularisation parameter (alpha)= 0.1
Mean Squared Error is 100.39526026677356
r^2 value is: 0.48533953468612


For regularisation parameter (alpha)= 0.5
Mean Squared Error is 101.65056319378898
r^2 value is: 0.4789044222434512


Ridge Regression analysis for split ratio 70:30
For regularisation parameter (alpha)= 0.001
Mean Squared Error is 65.59835106281098
r^2 value is: 0.5952933441091448


For regularisation parameter (alpha)= 0.005
Mean Squared Error is 64.94811749107579
r^2 value is: 0.5993049366278799


For regularisation parameter (alpha)= 0.01
Mean Squared Error is 64.5053187306285
r^2 value is: 0.6020367675759117


For regularisation parameter (alpha)= 0.05
Mean Squared Error is 64.30741816159086
r^2 value is: 0.6032577079836581


For regularisation parameter (alpha)= 0.1
Mean Squared Error is 64.7578330686953
r^2 value is: 0.6004788894941036


For regularisation parameter (alpha)= 0.5
Mean Squared Error is 65.67885139477552
r^2 value is: 0.594796700220699


Ridge Regression analysis for split ratio 90:10
For regularisation parameter (alpha)= 0.001
Mean Squared Error is 72.83695311694639
r^2 value is: 0.5822117606258782


For regularisation parameter (alpha)= 0.005
Mean Squared Error is 71.67631349788174
r^2 value is: 0.5888691173966691


For regularisation parameter (alpha)= 0.01
Mean Squared Error is 70.58866548392079
r^2 value is: 0.5951077988538946


For regularisation parameter (alpha)= 0.05
Mean Squared Error is 67.18786849394999
r^2 value is: 0.614614559174133


For regularisation parameter (alpha)= 0.1
Mean Squared Error is 66.12187617411726
r^2 value is: 0.6207290249148152


For regularisation parameter (alpha)= 0.5
Mean Squared Error is 65.07682752712981
r^2 value is: 0.6267233590488116

In [30]:
split_ratio=[0.8,0.6,0.7,0.9] #Ratios to be used for the question
for n in split_ratio:
    print('\033[1m' + ' Lasso Regression analysis for split ratio ' + str(int(n*100)) +":"+ str(int(100- n*100)) + '\033[0m')
    n_rows=np.ceil(n*413) #number of rows to be included in the train data

    train_data=df1.iloc[0:int(n_rows)]      #Defining the test and train data
    test_data=pd.DataFrame(df1.iloc[int(n_rows):df1.shape[0]]) 
    # Train the model
    lambda_values=[.001, 0.005, 0.01, 0.05, 0.1,0.5]
    for l in lambda_values:
        lasso = Lasso(alpha = l)
        lasso.fit(train_data.drop(columns=['Y house price of unit area']),  train_data.iloc[0:train_data.shape[0],6])
        y_pred = lasso.predict(test_data.drop(columns=['Y house price of unit area']))
        print("For regularisation parameter (alpha)=", l)
        print(" ")
 
    # calculate mean square error
        mean_squared_error_ridge = np.mean((y_pred - test_data.iloc[0:test_data.shape[0],6])**2)
        print("Mean Squared Error is" , mean_squared_error_ridge)
        
 
     # get r^2 value for lasso
        print("r^2 value is:",r2_score(test_data.iloc[0:test_data.shape[0],6], y_pred))
        print("")
        print("")

 Lasso Regression analysis for split ratio 80:20
For regularisation parameter (alpha)= 0.001

Mean Squared Error is 59.88479427317587
r^2 value is: 0.5943781957751479


For regularisation parameter (alpha)= 0.005

Mean Squared Error is 59.18185632426534
r^2 value is: 0.5991394538299815


For regularisation parameter (alpha)= 0.01

Mean Squared Error is 58.7501893790322
r^2 value is: 0.6020632932999974


For regularisation parameter (alpha)= 0.05

Mean Squared Error is 60.326491493339766
r^2 value is: 0.5913864175526713


For regularisation parameter (alpha)= 0.1

Mean Squared Error is 60.33352065916841
r^2 value is: 0.5913388064193241


For regularisation parameter (alpha)= 0.5

Mean Squared Error is 62.41140658129018
r^2 value is: 0.5772645184980916


 Lasso Regression analysis for split ratio 60:40
For regularisation parameter (alpha)= 0.001

Mean Squared Error is 98.18248507066063
r^2 value is: 0.49668297768373093


For regularisation parameter (alpha)= 0.005

Mean Squared Error is 98.1532097441131
r^2 value is: 0.4968330530273586


For regularisation parameter (alpha)= 0.01

Mean Squared Error is 98.53432190760091
r^2 value is: 0.49487934163823344


For regularisation parameter (alpha)= 0.05

Mean Squared Error is 102.34082882068061
r^2 value is: 0.475365884390347


For regularisation parameter (alpha)= 0.1

Mean Squared Error is 102.71980301591715
r^2 value is: 0.4734231329582168


For regularisation parameter (alpha)= 0.5

Mean Squared Error is 105.59128215177138
r^2 value is: 0.45870294811810697


 Lasso Regression analysis for split ratio 70:30
For regularisation parameter (alpha)= 0.001

Mean Squared Error is 65.54396189311967
r^2 value is: 0.5956288961257099


For regularisation parameter (alpha)= 0.005

Mean Squared Error is 64.7458291984062
r^2 value is: 0.6005529469379833


For regularisation parameter (alpha)= 0.01

Mean Squared Error is 64.22780582524781
r^2 value is: 0.603748873415213


For regularisation parameter (alpha)= 0.05

Mean Squared Error is 66.15493437550458
r^2 value is: 0.5918595234786661


For regularisation parameter (alpha)= 0.1

Mean Squared Error is 66.3392798508423
r^2 value is: 0.5907222107315651


For regularisation parameter (alpha)= 0.5

Mean Squared Error is 69.31720094245894
r^2 value is: 0.5723500341910139


 Lasso Regression analysis for split ratio 90:10
For regularisation parameter (alpha)= 0.001

Mean Squared Error is 72.69488987621244
r^2 value is: 0.5830266265515673


For regularisation parameter (alpha)= 0.005

Mean Squared Error is 70.77270185934151
r^2 value is: 0.5940521776344792


For regularisation parameter (alpha)= 0.01

Mean Squared Error is 68.71029744592383
r^2 value is: 0.6058820012595247


For regularisation parameter (alpha)= 0.05

Mean Squared Error is 64.60460805699735
r^2 value is: 0.629431980601227


For regularisation parameter (alpha)= 0.1

Mean Squared Error is 64.40044000897319
r^2 value is: 0.6306030758443721


For regularisation parameter (alpha)= 0.5

Mean Squared Error is 64.86048949851225
r^2 value is: 0.6279642605447964

Q2 1] Downloading the data

In [31]:
!gdown --id 1GTvFMLqhOE6E15kDymHU9XiJYzRRBwAq

Downloading...
From: https://drive.google.com/uc?id=1GTvFMLqhOE6E15kDymHU9XiJYzRRBwAq
To: /content/haberman.csv
100% 3.10k/3.10k [00:00<00:00, 2.63MB/s]

Q2 2] Loading the dataset and doing pre-processing

In [32]:
df2=pd.read_csv('/content/haberman.csv', header=None)
df2=df2.rename(columns={0:'Age', 1:'Year of operation',2:'Number of nodes',3:'Survival Status'})
display(df2)

     Age  Year of operation  Number of nodes  Survival Status
0     30                 64                1                1
1     30                 62                3                1
2     30                 65                0                1
3     31                 59                2                1
4     31                 65                4                1
..   ...                ...              ...              ...
301   75                 62                1                1
302   76                 67                0                1
303   77                 65                3                1
304   78                 65                1                2
305   83                 58                2                2

[306 rows x 4 columns]

Q2 3,4,5] Splitting the dataset

In [42]:
n_split=[0.8,0.6,0.7,0.9]  #Splitting ratios
tot_rows=df2.shape[0] #Number of rows in dataset 2
for n in n_split:
    print('\033[1m' + 'Logistic Regression analysis for split ratio ' + str(int(n*100)) +":"+ str(int(100- n*100)) + '\033[0m')
    n_rows=int(np.ceil(n*tot_rows))  #n_rows will be considered for train data, the rest into test data

    x_train=df2.iloc[0:n_rows, 0:3] #data matrix for train data
    y_train=df2.iloc[0:n_rows, 3]  #y column for train data
    x_test= df2.iloc[n_rows:tot_rows, 0:3] #data matrix for testing
    y_test=pd.DataFrame(df2.iloc[n_rows:tot_rows, 3])   #y column for testing

    #Finding coefficents and intercepts on the model trained on logistic regression
    model.fit(x_train,y_train)
    print("Intercept of the model is", model.intercept_)
    print("The coefficients are", model.coef_)


    #Predicting the Survival status 
    y_pred=model.predict(x_test)
    display(pd.DataFrame(y_pred).rename(columns={0:'Prediction'}))
    
    #Cumulative Classification error from loops
    cm_error=0
    c_error=0
    n_obs=int(np.ceil(y_pred.shape[0]*1))
    for i in range(0,n_obs,1):
        cm_error=cm_error + np.abs(int(pd.DataFrame(y_pred).iloc[i,0]-int(y_test.iloc[i,0])))
    c_error=cm_error/y_test.shape[0]
    print("The classification error is" ,c_error) 
    print(" ")
    print(" ")

Logistic Regression analysis for split ratio 80:20
Intercept of the model is [-0.52976252]
The coefficients are [[ 0.02057652 -0.03053873  0.08918028]]

    Prediction
0            1
1            1
2            1
3            1
4            1
..         ...
56           1
57           1
58           1
59           1
60           1

[61 rows x 1 columns]

The classification error is 0.26229508196721313


Logistic Regression analysis for split ratio 60:40
Intercept of the model is [-0.67179222]
The coefficients are [[ 0.04869743 -0.04640544  0.08363301]]

     Prediction
0             1
1             2
2             1
3             1
4             2
..          ...
117           2
118           1
119           2
120           2
121           2

[122 rows x 1 columns]

The classification error is 0.22950819672131148


Logistic Regression analysis for split ratio 70:30
Intercept of the model is [-0.53316845]
The coefficients are [[ 0.0235733  -0.03229411  0.08728731]]

    Prediction
0            2
1            1
2            1
3            1
4            1
..         ...
86           1
87           1
88           1
89           1
90           1

[91 rows x 1 columns]

The classification error is 0.24175824175824176


Logistic Regression analysis for split ratio 90:10
Intercept of the model is [-0.41738421]
The coefficients are [[ 0.01961775 -0.03170187  0.08557289]]

    Prediction
0            1
1            1
2            1
3            1
4            1
5            1
6            1
7            1
8            1
9            1
10           1
11           2
12           1
13           1
14           1
15           1
16           1
17           1
18           1
19           1
20           1
21           1
22           1
23           1
24           1
25           1
26           1
27           1
28           1
29           1

The classification error is 0.26666666666666666